### ISSUE TITLE
Network I/O Error

### ISSUE THREAD

**Issue by bdubn** [spamwax/rusty-pin#1]
DEBUG 2018-05-03T02:42:17Z: rusty_pin::pinboard::api:   url: "https://api.pinboard.in/v1/posts/all?format=json&auth_token=<token>"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "Network IO error" }', libcore/result.rs:945:5

Cannot create new bookmarks / search existing bookmarks or tags. Thoughts?

**Comment by spamwax** [comment]
This just started happening or is this your first try at workflow?

The error indicates that plugin couldn't talk to pinboard at all.
This can happen if you/pinboard have network connection issues.
it could happen if the auth_token is malformed!

- Make sure you delete the `settings.json` from workflow's data dir (`~/Library/Application Support/Alfred 3/Workflow Data/cc.hamid.alfred-pinboard-rs`)
- The setup your authorization token again. Your token should be something like `bdubn:A7983`

If this doesn't help, please post entire log from Alfred's window so I can have a better insight.

And if you don't mind, open a new issue in the main repository of the workflow.
