### ISSUE TITLE
Show "You have the latest version of workflow" as last entry in search list

### ISSUE THREAD

**Issue by sent-hil** [spamwax/rusty-pin#4]
First of all, great plugin. I use it nearly every hour, it's been incredibly useful and time saving, so thank you!

The one minor issue I'm having is when I search for something, the version checker shows up in the list of search results in middle of results before the search results. While by itself it isn't a problem, the checker is slower to appear than search results. So I will type something, use down arrow to go to result I want, but then the version checker will take its place and I will have to scroll down one more.

It would be great if the version label appears last or only appears if there's something to update.

![1](https://user-images.githubusercontent.com/164864/84174500-86cf2d80-aa33-11ea-9eb0-b3e5ee5c28b3.jpg)

**Comment by spamwax** [comment]
this is interesting, I specifically insert the version checker item to the end of list returned to Alfred.
can this be related to the locale/lang settings of your mac?
